include_guard()
if(NOT WIN32)
    string(ASCII 27 Esc)
    set(ColorReset      "${Esc}[m")
    set(ColorBold       "${Esc}[1m")
    set(ColorRed        "${Esc}[31m")
    set(ColorGreen      "${Esc}[32m")
    set(ColorYellow     "${Esc}[33m")
    set(ColorBoldRed    "${Esc}[1;31m")
    set(ColorBoldGreen  "${Esc}[1;32m")
    set(ColorBoldYellow "${Esc}[1;33m")
endif()
