if((${CMAKE_SOURCE_DIR} STREQUAL ${PROJECT_SOURCE_DIR}) OR (NOT DEFINED ENABLE_IPO))
    option(ENABLE_IPO "Enable Interprocedural Optimization, aka Link Time Optimization (LTO)" OFF)
    message(STATUS "ENABLE_IPO == ${ENABLE_IPO}")
endif()
cmake_dependent_option(${PROJECT_NAME}_IPO "Enable Interprocedural Optimization, aka Link Time Optimization (LTO)" OFF "NOT ENABLE_IPO" ON)
message(STATUS "${PROJECT_NAME}_IPO == ${${PROJECT_NAME}_IPO}")


function(enable_ipo)
    if(${PROJECT_NAME}_IPO)
        include(CheckIPOSupported)
        check_ipo_supported(RESULT _ipo_supported OUTPUT output)
        if(_ipo_supported)
            set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON PARENT_SCOPE)
        else()
            message(SEND_ERROR "${ColorRed}IPO is not supported: ${output}${ColorReset}")
        endif()
    endif()
endfunction()
