include(${CMAKE_CURRENT_LIST_DIR}/colors.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/prefix.cmake)

macro(SetOptionNames)
    set(prefix "")
    GetProjectPrefix(prefix)
    set(OPT_WERROR           ${prefix}_WERROR)
    set(OPT_TESTS            ${prefix}_TESTS)
    set(OPT_COVERAGE         ${prefix}_COVERAGE)
    set(OPT_SANITIZE_ADDRESS ${prefix}_SANITIZE_ADDRESS)
    set(OPT_SANITIZE_LEAK    ${prefix}_SANITIZE_LEAK)
    set(OPT_SANITIZE_THREAD  ${prefix}_SANITIZE_THREAD)
    set(OPT_SANITIZE_UB      ${prefix}_SANITIZE_UDEFINED_BEHAVIOR)
    message(STATUS "${ColorYellow}${OPT_WERROR}          ${ColorReset}")
    message(STATUS "${ColorYellow}${OPT_TESTS}           ${ColorReset}")
    message(STATUS "${ColorYellow}${OPT_COVERAGE}        ${ColorReset}")
    message(STATUS "${ColorYellow}${OPT_SANITIZE_ADDRESS}${ColorReset}")
    message(STATUS "${ColorYellow}${OPT_SANITIZE_LEAK}   ${ColorReset}")
    message(STATUS "${ColorYellow}${OPT_SANITIZE_THREAD} ${ColorReset}")
    message(STATUS "${ColorYellow}${OPT_SANITIZE_UB}     ${ColorReset}")
endmacro()

macro(SetOptions)
    SetOptionNames()
    option(${OPT_WERROR} "Enable warning as errors for ${CMAKE_PROJECT_NAME}" ON)
    option(${OPT_TESTS} "Build ${CMAKE_PROJECT_NAME} tests" ON)
    option(${OPT_COVERAGE} "Generate ${CMAKE_PROJECT_NAME} code coverage" OFF)
    option(${OPT_SANITIZE_ADDRESS} "Enable address-sanitizer for ${CMAKE_PROJECT_NAME}" OFF)
    option(${OPT_SANITIZE_LEAK} "Enable leak-sanitizer for ${CMAKE_PROJECT_NAME}" OFF)
    option(${OPT_SANITIZE_THREAD} "Enable thread-sanitizer for ${CMAKE_PROJECT_NAME}" OFF)
    option(${OPT_SANITIZE_UB} "Enable undefined-behavior-sanitizer for ${CMAKE_PROJECT_NAME}" OFF)

    if (NOT CMAKE_BUILD_TYPE STREQUAL Debug)
        if (CODE_COVERAGE)
            message(FATAL_ERROR
                "${ColorBoldRed}CODE_COVERAGE=ON valid only for CMAKE_BUILD_TYPE=Debug${ColorReset}"
            )
        endif()
        if (SANITIZE_ADDRESS OR SANITIZE_LEAK OR SANITIZE_THREAD OR SANITIZE_UNDEFINED_BEHAVIOR)
            message(FATAL_ERROR
                "${ColorBoldRed}Sanitizers can be used only with CMAKE_BUILD_TYPE=Debug${ColorReset}"
            )
        endif()
    endif()
endmacro()
